version: '3.4'

services:

  nginx:
    depends_on:
      - api
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  db:
    container_name: postgres-db
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 6544:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
       - ./data:/var/lib/postgresql/data
  
  api:
    depends_on:
      - db
    build:
      context: ./be
      target: production
    expose:
      - 5000
    environment:
      ORIGIN: ${PROD_ORIGIN}
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}